name: react
type: service
from: nginx
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.14"
title: Nginx (React)
labels:
- nginx
- react

build:
  connect: true
  boilerplates:
  - name: react
    title: React boilerplate
    repo: https://github.com/wodby/react-boilerplate
    branch: main
